config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'users/edit'
  # get 'post_images/new'
  # get 'post_images/index'
  # get 'post_images/show'
  root to: "homes#top"
  get 'homes/about'
  devise_for :users
  resources :users, only: [:show, :edit] 
  resources :post_images, only: [:new, :index, :show, :create, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  

   

  # devise_for :users
  # get 'homes/top'
  root to: "homes#top"
  get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
# resources メソッドは、ルーティングを一括して自動生成してくれる機能です。
# post_comments#creates しようと思ったら　:post_image_idがないとコメント投稿できなくなる
# params[:post_image_id]でPostImageのidが取得できるようになります。

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    validates :shop_name, presence: true
    validates :image, presence: true
    
    

    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        image
    end
    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

# favorited_by?メソッドを作成します。 このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。 存在していればtrue、存在していなければfalseを返すようにしています。

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  # get_profile_imageは動作を表すメソッドになる　カラム名と区別しないとけない　全く別物のものと考える

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top]

    # ログイン認証が済んでいない状態でトップページ以外の画面にアクセスしても、ログイン画面へリダイレクトするようになります。 また、ログイン認証が済んでいる場合には全てのページにアクセスすることができます。
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        post_images_path
    end
    def after_sign_out_path_for(resource)
        homes_about_path
    end
    protected


    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

# このように記述することで、devise利用の機能（ユーザ登録、ログイン認証など）が使われる前に
# configure_permitted_parametersメソッドが実行されます。
# ※「Sign up」はユーザ登録、「Sign in」はログインのこと
# デフォルトではユーザ登録後の遷移先はルートパスになっています。
# また、ユーザ登録後はログイン状態にあります。

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        post_image = PostImage.find(params[:post_image_id])
        # favorite.user_id = current_user.id
        # post_image_id = post_image.id
        # favorite = Favorite.new(post_image_id: post_image.id)
        favorite = current_user.favorites.new(post_image_id: post_image.id)
        favorite.save
        redirect_to post_image_path(post_image)
    end
    def destroy
        post_image = PostImage.find(params[:post_image_id])
        # favorite.user_id = current_user.id
        # post_image_id = post_image.id
        favorite = current_user.favorites.find_by(post_image_id: post_image.id)
        favorite.destroy
        redirect_to post_image_path(post_image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    def create
        post_image = PostImage.find(params[:post_image_id])
        comment = PostComment.new(post_comment_params)
        comment.user_id = current_user.id
        comment.post_image_id = post_image.id
        comment.save
        redirect_to post_image_path(post_image)
    end
    def destroy
        PostComment.find(params[:id]).destroy
        redirect_to post_image_path(params[:post_image_id])
    end
    private
    def post_comment_params
        params.require(:post_comment).permit(:comment)
    end
    
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    # @post_image.user_id,つまりこの投稿の user_id としてcurrent_user.id の値を代入する、という意味
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  # saveメソッドはデータベースへレコードを保存するメソッドですが、メソッドの結果を同時に返してくれます。
  # 保存が成功した場合はtrue、失敗した場合はfalseを返します。


  def index
    @post_images = PostImage.page(params[:page])
    # pageメソッドは、kaminariをインストールしたことで使用可能になったメソッドです。
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
    # @post_comments = @post_image.post_comments
  end
  def destroy
    @post_image = PostImage.find(params[:id])
    # @post_image.user_id = current_user.id
    @post_image.destroy
    redirect_to post_images_path
  end
  private
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
    # 結果的に、全体の投稿ではなく、個人が投稿したもの全てを表示できます。
  end

  def edit
    @user = User.find(params[:id])
  end
end
# ユーザーの詳細ページでは、ユーザー情報に加えて、ユーザーが投稿したPostImageモデルの一覧も詳細ページに表示させていきます。

# @user.post_imagesに格納されているデータは複数あるため
# @post_images.user.id,@post_images.user.nameのように
# 関連づけられているモデルのカラムを操作することはできません。
# each文を使用して、一つずつデータを確認した上で、カラムを操作する必要があります。

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
Aboutだよ

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
<div>
    <p>投稿画像 
    <%= link_to post_image_path(post_image.id) do %>
        <%= image_tag post_image.get_image, size: '200x200'  %>
    <% end %>
    </p>
    <p>ユーザーの顔写真<%= image_tag 'sample-author1.jpg', width: '10%', height: '10%' %></p>
    <p>ショップ名<%= post_image.shop_name %></p>
    <p>説明<%= post_image.caption %></p>
    <p>ユーザーネーム<%= post_image.user.name %></p>
</div>
<% end %>
<%= paginate @post_images %>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<% if @post_image.errors.any? %>
    <%= @post_image.errors.count %>件のエラーがあります
<ul>
<% @post_image.errors.full_messages.each do |message| %>
    <li><%= message %></li>
<% end %>
</ul>

<% end %>

<%= form_with model: @post_image do |f| %>
<h4>画像</h4>
<%= f.file_field :image, accept: "image/*"%>
<h4>ショップ名</h4>
<%= f.text_field :shop_name %>
<h4>説明</h4>  
<%= f.text_area :caption %> 
<%= f.submit "投稿します"%>
<% end %>

app/views/post_images/show.html.erb
<div>
    <h1>マイページ</h1>
    <div>
        投稿した画像<%= image_tag @post_image.get_image, size: '200x200'%>
    </div>
        <p>ショップ名<%= @post_image.shop_name %></p>
        <p>説明<%= @post_image.caption%></p>
        <p>ユーザーの顔写真 <%= image_tag 'sample-author1.jpg', width: '10%', height: '10%'%></p>
        <p>ユーザーの名前<%= @post_image.user.name %></p>
        <p>投稿日 <%= @post_image.created_at.strftime("%Y年%m月%d日") %></p>
        <p>
        <% if @post_image.user_id == current_user.id %>
            <%= link_to "削除", post_image_path(@post_image), method: :delete, data: { confirm: "【確認】投稿した履歴を削除してもよろしいですか？" }%>
        <% end %>
        </p>  
        <% if @post_image.favorited_by?(current_user) %>
        <p>
        <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
            ♥<%= @post_image.favorites.count %> いいね
        <% end %>
        </p>
        <% else %>
        <p>
        <%= link_to post_image_favorites_path(@post_image), method: :post do %>
            ♡<%= @post_image.favorites.count %> いいね
        <% end %>
        </p>
        <% end %>
</div>
<div>
    <h1>コメント一覧</h1>
    <p>コメント件数<%= @post_image.post_comments.count %></p>
    <% @post_image.post_comments.each do |post_comment| %>
        <p>ユーザーの顔写真<%= image_tag post_comment.user.get_profile_image, size: "100x100" %></p>
        <p>ユーザーの名前<%= post_comment.user.name %></p>
        <p>投稿日<%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
        <p>コメント<%= post_comment.comment %></p>
        <% if post_comment.user_id == current_user.id %>
            <%= link_to "delete",  post_image_post_comment_path(post_comment.post_image_id, post_comment.id), method: :delete, data: { confirm: "【確認】投稿した履歴を削除してもよろしいですか？" } %>
        <% end %>
    <% end %>
    





        
    
</div>

<div>
    <h1>コメント投稿できるよ</h1>
    <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: "5", placeholder: "コメント入れてね " %>
    <%= f.submit "send" %>
    <% end %>
    
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集画面</h2>
<%= form_with model: @user do |f| %>
    <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: "name"%><br>
    <label for="inputImage">profile_image</label>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", id:"inputName" %><br>
    <%= f.submit "保存する" %>
<% end %>

app/views/users/show.html.erb
<div>
    <h1>ユーザーの詳細</h1>
    <h3>ユーザーの名前<%= @user.name %></h3>
    <h3>ユーザーの顔写真<%= image_tag @user.get_profile_image, size: "100x100" %></h3>
    <h3><%= link_to "プロフィール編集", edit_user_path(@user) %></h3>
</div>
<% @post_images.each do |post_image| %>
<div>
<h1>ユーザーの投稿したデータ一覧</h1>
<p>投稿した画像
<%= link_to post_image_path(post_image)  do %>
    <%= image_tag post_image.get_image, size: "200x200"%>

<% end %>
</p>
<p>お店の名前<%= post_image.shop_name %></p>
<p>説明<%= post_image.caption %></p>
<p>ユーザーの名前<%= post_image.user.name %></p>
<p>ユーザーの顔写真 <%= image_tag post_image.user.get_profile_image, size: "100x100" %></p>
</div>
<% end %>

<%= paginate @post_images %>